# Generated by Django 5.0.4 on 2024-05-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherstudent',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.students'),
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.teachers'),
        ),
    ]
